# Generated by Django 5.1 on 2024-12-15 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_reply_check_contact_reply_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='reply_check',
        ),
    ]
